version: "3"
services:
  mariadb:
    hostname: mariadb
    image: linuxserver/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TZ}
    networks:
      - drupal_network
    restart: unless-stopped
    volumes:
      - /home/jcdock/containers/drupal/database:/config
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 4081:80
    networks:
      - drupal_network
    restart: unless-stopped
      
  druapl:
    container_name: drupal
    hostname: drupal
    image: drupal:latest
    networks:
      - drupal_network
    ports:
      - 4080:80
    restart: unless-stopped
    volumes:
      - /home/jcdock/containers/drupal/modules:/var/www/html/modules
      - /home/jcdock/containers/drupal/profiles:/var/www/html/profiles
      - /home/jcdock/containers/drupal/themes:/var/www/html/themes
      - /home/jcdock/containers/drupal/sites:/var/www/html/sites
    depends_on:
      - mariadb

networks:
  drupal_network:
